name: Code Agent

permissions:
  contents: write
  pull-requests: write
  issues: write

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  code-agent:
    runs-on: ubuntu-latest
    if: ${{ github.event.sender.type != 'Bot' }}
    steps:
      # Checkout the target repo (your code)
      - name: Checkout your repository
        uses: actions/checkout@v4

      # Checkout the Code Agent repo (used as an action)
      - name: Checkout Code Agent source
        uses: actions/checkout@v4
        with:
          repository: potproject/code-agent
          path: code-agent

      # 🛠️ Install the latest Claude CLI (bypass the outdated one)
      - name: Install latest Claude CLI
        run: |
          npm install -g claude-code@latest
          claude --version

      # ✅ Run Code Agent from local checkout, with Claude config
      - name: Run Code Agent with Claude
        uses: ./code-agent
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          anthropic-model: "claude-3-sonnet-20240229"
          anthropic-small-fast-model: "claude-3-haiku-20240307"
