name: Code Agent

permissions:
  contents: write
  pull-requests: write
  issues: write

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  code-agent:
    runs-on: ubuntu-latest
    if: ${{ github.event.sender.type != 'Bot' }}
    steps:
      - uses: potproject/code-agent@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

          # ✅ Claude API Key (required)
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}

          # ✅ Claude base URL (optional — keep default unless you're using a proxy or Bedrock)
          anthropic-base-url: "https://api.anthropic.com"

          # ✅ Main Claude model (e.g. Sonnet is good for general purpose coding)
          anthropic-model: "claude-3-sonnet-20240229"

          # ✅ Optional small/fast Claude model (used for quick tasks)
          anthropic-small-fast-model: "claude-3-haiku-20240307"

          # ❌ REMOVE or COMMENT OUT OpenAI keys since you're not using Codex
          # openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          # openai-base-url: "https://api.openai.com"
